// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// schaefer
NumericMatrix schaefer(NumericVector startbt, double ri, NumericVector ct, NumericVector intbio, NumericVector endbio, int i, int nyr, int ni, double ki, double sigR, double duncert, int int_yr_i, int end_yr);
RcppExport SEXP _portedcmsy_schaefer(SEXP startbtSEXP, SEXP riSEXP, SEXP ctSEXP, SEXP intbioSEXP, SEXP endbioSEXP, SEXP iSEXP, SEXP nyrSEXP, SEXP niSEXP, SEXP kiSEXP, SEXP sigRSEXP, SEXP duncertSEXP, SEXP int_yr_iSEXP, SEXP end_yrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type startbt(startbtSEXP);
    Rcpp::traits::input_parameter< double >::type ri(riSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ct(ctSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type intbio(intbioSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type endbio(endbioSEXP);
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< int >::type nyr(nyrSEXP);
    Rcpp::traits::input_parameter< int >::type ni(niSEXP);
    Rcpp::traits::input_parameter< double >::type ki(kiSEXP);
    Rcpp::traits::input_parameter< double >::type sigR(sigRSEXP);
    Rcpp::traits::input_parameter< double >::type duncert(duncertSEXP);
    Rcpp::traits::input_parameter< int >::type int_yr_i(int_yr_iSEXP);
    Rcpp::traits::input_parameter< int >::type end_yr(end_yrSEXP);
    rcpp_result_gen = Rcpp::wrap(schaefer(startbt, ri, ct, intbio, endbio, i, nyr, ni, ki, sigR, duncert, int_yr_i, end_yr));
    return rcpp_result_gen;
END_RCPP
}
// timesTwo
NumericVector timesTwo(NumericVector x);
RcppExport SEXP _portedcmsy_timesTwo(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(timesTwo(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_portedcmsy_schaefer", (DL_FUNC) &_portedcmsy_schaefer, 13},
    {"_portedcmsy_timesTwo", (DL_FUNC) &_portedcmsy_timesTwo, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_portedcmsy(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
