# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

schaefer <- function(startbt, ri, ct, intbio, endbio, i, nyr, ni, ki, sigR, duncert, int_yr_i, end_yr) {
    .Call(`_portedcmsy_schaefer`, startbt, ri, ct, intbio, endbio, i, nyr, ni, ki, sigR, duncert, int_yr_i, end_yr)
}

timesTwo <- function(x) {
    .Call(`_portedcmsy_timesTwo`, x)
}

